#!/bin/sh

bspc config focused_border_color "#0a9dff"
bspc config normal_border_color "#d9cec3"

bspc config border_width                4
bspc config window_gap                  12
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config click_to_focus              true

bspc monitor -d I II III IV V VI VII VIII IX X

dotfiles/bar/panel &> .panel.log &
