#!/bin/bash

get() {
    echo -n $2 | sed -e "s/.*$1 \(\w*\).*/\1/"
}

. dotfiles/bar/panel_colors

while read -r line ; do
	case $line in
		S*)
			# clock output
			sys=" %{F$COLOR_FREE_FG}%{B$COLOR_FREE_BG}date: %{F$COLOR_TITLE_FG}%{F$COLOR_TITLE_FG}%{B$COLOR_TITLE_BG}${line#?}%{B-}%{F-} "
			;;
		T*)
			# xtitle output
			title=" %{F$COLOR_FREE_FG}%{B$COLOR_FREE_BG}->> %{F$COLOR_TITLE_FG}%{B$COLOR_TITLE_BG}${line#?}%{B-}%{F-} "
			;;
                V*)
                        # pamixer output
                        volume=" %{F$COLOR_FREE_FG}%{B$COLOR_FREE_BG}%{A5:pamixer -d 5:}%{A4:pamixer -i 5:}vol: %{F$COLOR_TITLE_FG}%{B$COLOR_TITLE_BG}${line#?}%{A}%{A}%{B-}%{F-} "
                        ;;
                N*)
                        # network output
                        network=" %{F$COLOR_FREE_FG}%{B$COLOR_FREE_BG}net: %{F$COLOR_TITLE_FG}%{B$COLOR_TITLE_BG}${line#?}%{B-}%{F-} "
                        ;;
                B*)
                        # battery output
                        status=$(get 'status' "${line#?}")
                        power=$(get 'power' "${line#?}")

                        battery=" %{F$COLOR_FREE_FG}%{B$COLOR_FREE_BG}pow: "

                        if [ $power = 'Charging' ]; then
                            battery=$battery"%{F$COLOR_SYS_FG}%{B$COLOR_SYS_BG}charging "
                        elif [ $power = 'Discharging' ]; then
                            battery=$battery"%{F$COLOR_SYS_FG}%{B$COLOR_SYS_BG}discharging "
                        fi

                        if [ $status -gt 20 ]; then
                            battery=$battery"%{F$COLOR_TITLE_FG}%{B$COLOR_TITLE_BG}$status%%{B-}%{F-} "
                        else
                            battery=$battery"%{F$COLOR_DEFAULT_BG}%{B$COLOR_FOCUSED_URGENT_BG} $status% %{B-}%{F-} "
                        fi

                        ;;
                I*)     # inbox output
                        inbox=" %{F$COLOR_FREE_FG}%{B$COLOR_FREE_BG}mail: "

                        if [ ${line#?} -gt 0 ]; then
                            inbox=$inbox"%{F$COLOR_SYS_FG}%{B$COLOR_TITLE_BG}${line#?}%{B-}%{F-} "
                        else
                            inbox=$inbox"%{F$COLOR_TITLE_FG}%{B$COLOR_TITLE_BG}${line#?}%{B-}%{F-} "
                        fi

                        ;;
                D*)     # desktop number
                        desktop=" %{F$COLOR_FREE_FG}%{B$COLOR_FREE_BG}desktop: %{F$COLOR_TITLE_FG}%{B$COLOR_TITLE_BG}${line#?}%{B-}%{F-} "
                        ;;
	esac
	printf "%s\n" "%{c}${desktop}${inbox}${network}${volume}${battery}${sys}"
done
