#!/bin/env bash

if xdo id -a "$PANEL_WM_NAME" > /dev/null ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

network() {
    read lo int1 int2 <<< `ip link | sed -n 's/^[0-9]: \(.*\):.*$/\1/p'`
    if iwconfig $int1 >/dev/null 2>&1; then
        wifi=$int1
        eth0=$int2
    else
        wifi=$int2
        eth0=$int1
    fi
    ip link show $eth0 | grep 'state UP' >/dev/null && int=$eth0 ||int=$wifi

    #int=eth0

    ping -c 1 8.8.8.8 >/dev/null 2>&1 && 
        echo "$int" || echo "$disconnected"
}

battery() {
    BATC=$(cat /sys/class/power_supply/BAT1/capacity)
    BATS=$(cat /sys/class/power_supply/BAT1/status)

    read ac <<< `echo -n "power $BATS"`
    read status <<< `echo -n "status $BATC"`

    echo -n "$ac $status"
}

desktop() {
    xprop -root _NET_CURRENT_DESKTOP | awk '{print $3}'
}

groups() {
    # ALL=$(windows -l | grep 'group.' | sed 's/[^0-9]//g' | tr '\n' ',' | sed 's/.$//')
    GROUPS=$(windows -l | grep 'group.' | sed 's/[^0-9]//g')
    ACTIVE_WID=$(windows -f $(pfw) | grep -o .$)
    GROUPS_DIR=/tmp/fyre/groups
    INACTIVE=""
    ACTIVE=""

    if [ -f "$GROUPS_DIR/inactive" ]; then
        INACTIVE=$(cat /tmp/fyre/groups/inactive)
    fi

    if [ -f "$GROUPS_DIR/active" ]; then
        ACTIVE=$(cat /tmp/fyre/groups/active)
    fi

    if [ -z "$ACTIVE_WID" ]
    then
        ACTIVE_WID="X"
    fi

    echo "$ACTIVE_WID:$ACTIVE:$INACTIVE"
}

inbox() {
    notmuch count tag:unread
}

xtitle -sf 'T%s' > "$PANEL_FIFO" &

while :; do
    echo 'S'$(date '+%Y-%m-%d %H:%M')
    sleep 1
done > "$PANEL_FIFO" &

while :; do
    echo 'V'$(pamixer --get-volume)
    sleep 0.2
done > "$PANEL_FIFO" &

while :; do
    echo 'N'$(network)
    sleep 5
done > "$PANEL_FIFO" &

while :; do
    echo 'I'$(inbox)
    sleep 2
done > "$PANEL_FIFO" &

if [ -d /sys/class/power_supply/BAT1 ]; then
    while :; do
    echo 'B'$(battery)
    sleep 2
    done > "$PANEL_FIFO" &
fi

while :; do
    echo 'D'$(desktop)
    sleep 0.2
done > "$PANEL_FIFO" &

while :; do
    echo 'G'$(groups)
    sleep 0.2
done > "$PANEL_FIFO" &

. dotfiles/bar/panel_colors

dotfiles/bar/panel_bar < "$PANEL_FIFO" | lemonbar -a 32 -n "$PANEL_WM_NAME" -g x$PANEL_HEIGHT -f "$PANEL_FONT" -F "$COLOR_DEFAULT_FG" -B "$COLOR_DEFAULT_BG" | sh &

wid=$(xdo id -a "$PANEL_WM_NAME")
tries_left=20
while [ -z "$wid" -a "$tries_left" -gt 0 ] ; do
	sleep 0.05
	wid=$(xdo id -a "$PANEL_WM_NAME")
        echo "wid: $wid"
	tries_left=$((tries_left - 1))
done

[ -n "$wid" ] && ignw -s "$wid"

wait
