#!/bin/bash
#
# Example panel for lemonbar

get() {
    echo -n $2 | sed -e "s/.*$1 \(\w*\).*/\1/"
}

. dotfiles/bar/panel_colors

num_mon=$(bspc query -M | wc -l)

while read -r line ; do
	case $line in
		S*)
			# clock output
			sys=" %{F$COLOR_TITLE_FG}%{B$COLOR_TITLE_BG}${line#?}%{B-}%{F-} "
			;;
		T*)
			# xtitle output
			title="%{F$COLOR_TITLE_FG}%{B$COLOR_TITLE_BG} ${line#?} %{B-}%{F-}"
			;;
                V*)
                        # pamixer output
                        volume=" %{F$COLOR_FREE_FG}%{B$COLOR_FREE_BG}%{A5:pamixer -d 5:}%{A4:pamixer -i 5:}vol: %{F$COLOR_TITLE_FG}%{B$COLOR_TITLE_BG}${line#?}%%{A}%{A}%{B-}%{F-} "
                        ;;
                N*)
                        # network output
                        network=" %{F$COLOR_FREE_FG}%{B$COLOR_FREE_BG}net: %{F$COLOR_TITLE_FG}%{B$COLOR_TITLE_BG}${line#?}%{B-}%{F-} "
                        ;;
                B*)
                        # battery output
                        status=$(get 'status' "${line#?}")
                        power=$(get 'power' "${line#?}")

                        battery=" %{F$COLOR_FREE_FG}%{B$COLOR_FREE_BG}pow: "

                        if [ $power = 'Charging' ]; then
                            battery=$battery"%{F$COLOR_SYS_FG}%{B$COLOR_SYS_BG}charging "
                        elif [ $power = 'Discharging' ]; then
                            battery=$battery"%{F$COLOR_SYS_FG}%{B$COLOR_SYS_BG}discharging "
                        fi

                        if [ $status -gt 20 ]; then
                            battery=$battery"%{F$COLOR_TITLE_FG}%{B$COLOR_TITLE_BG}$status%%{B-}%{F-} "
                        else
                            battery=$battery"%{F$COLOR_DEFAULT_BG}%{B$COLOR_FOCUSED_URGENT_BG} $status% %{B-}%{F-} "
                        fi

                        ;;
                I*)     # inbox output
                        inbox=" %{F$COLOR_FREE_FG}%{B$COLOR_FREE_BG}mail: "

                        if [ ${line#?} -gt 0 ]; then
                            inbox=$inbox"%{F$COLOR_DEFAULT_BG}%{B$COLOR_SYS_FG} ${line#?} %{B-}%{F-} "
                        else
                            inbox=$inbox"%{F$COLOR_TITLE_FG}%{B$COLOR_TITLE_BG}${line#?}%{B-}%{F-} "
                        fi

                        ;;
		W*)
			# bspwm's state
			wm=""
			IFS=':'
			set -- ${line#?}
			while [ $# -gt 0 ] ; do
				item=$1
				name=${item#?}
				case $item in
					[mM]*)
						[ $num_mon -lt 2 ] && shift && continue
						case $item in
							m*)
								# monitor
								FG=$COLOR_MONITOR_FG
								BG=$COLOR_MONITOR_BG
								;;
							M*)
								# focused monitor
								FG=$COLOR_FOCUSED_MONITOR_FG
								BG=$COLOR_FOCUSED_MONITOR_BG
								;;
						esac
						wm="${wm}%{F${FG}}%{B${BG}}%{A:bspc monitor -f ${name}:} ${name} %{A}%{B-}%{F-}"
						;;
					[fFoOuU]*)
						case $item in
							f*)
								# free desktop
								FG=$COLOR_FREE_FG
								BG=$COLOR_FREE_BG
								;;
							F*)
								# focused free desktop
								FG=$COLOR_FOCUSED_FREE_FG
								BG=$COLOR_FOCUSED_FREE_BG
								;;
							o*)
								# occupied desktop
								FG=$COLOR_OCCUPIED_FG
								BG=$COLOR_OCCUPIED_BG
								;;
							O*)
								# focused occupied desktop
								FG=$COLOR_FOCUSED_OCCUPIED_FG
								BG=$COLOR_FOCUSED_OCCUPIED_BG
								;;
							u*)
								# urgent desktop
								FG=$COLOR_URGENT_FG
								BG=$COLOR_URGENT_BG
								;;
							U*)
								# focused urgent desktop
								FG=$COLOR_FOCUSED_URGENT_FG
								BG=$COLOR_FOCUSED_URGENT_BG
								;;
						esac
						wm="${wm}%{F${FG}}%{B${BG}}%{A:bspc desktop -f ${name}:} ${name} %{A}%{B-}%{F-}"
						;;
					[LTG]*)
						# layout, state and flags
						wm="${wm}%{F$COLOR_STATE_FG}%{B$COLOR_STATE_BG} ${name} %{B-}%{F-}"
						;;
				esac
				shift
			done
			;;
	esac
	printf "%s\n" "%{l}${wm}%{c}${title}%{r}${inbox}${network}${volume}${battery}${sys}"
done
