#!/bin/env bash

if xdo id -a "$TITLE_BAR_WM_NAME" > /dev/null ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$TITLE_BAR_FIFO" ] && rm "$TITLE_BAR_FIFO"
mkfifo "$TITLE_BAR_FIFO"

xtitle -sf 'T%s' > "$TITLE_BAR_FIFO" &

. dotfiles/bar/panel_colors

dotfiles/bar/title_bar < "$TITLE_BAR_FIFO" | lemonbar -b -a 32 -n "$PANEL_WM_NAME" -g 500x$PANEL_HEIGHT+1384+32 -f "$PANEL_FONT" -F "$COLOR_DEFAULT_FG" -B "$COLOR_DEFAULT_BG" | sh &

wid=$(xdo id -a "$TITLE_BAR_WM_NAME")
tries_left=20
while [ -z "$wid" -a "$tries_left" -gt 0 ] ; do
	sleep 0.05
	wid=$(xdo id -a "$TITLE_BAR_WM_NAME")
	tries_left=$((tries_left - 1))
done
[ -n "$wid" ] && xdo above -t "$(xdo id -N 2bwm -n root | sort | head -n 1)" "$wid"

wait
