# -*- eval: (ansible +1) -*-

- hosts: all

  tasks:
    - name: install packages
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - git
        - zsh

    - name: create zfunctions directory
      file:
        state: directory
        path: $HOME/.zfunctions

    - name: clone pure prompt
      git:
        repo: https://github.com/sindresorhus/pure.git
        dest: $HOME/.local/pure

    - name: install pure prompt
      file:
        src: $HOME/.pure/{{ item.src }}
        dest: $HOME/.zfunctions/{{ item.dest }}
        state: link
      with_items:
        - { src: async.zsh, dest: async }
        - { src: pure.zsh, dest: prompt_pure_setup }

    - name: clone dotfiles
      git:
        repo: https://github.com/bkruczyk/dotfiles.git
        dest: $HOME/.local/dotfiles

    - name: symlink configs
      file:
        src: $HOME/.local/dotfiles/{{ item.name }}/{{ item.path }}
        dest: $HOME/{{ item.path }}
        state: link
      with_items:
        - { name: shell, path: .aliases }
        - { name: shell, path: .env }
        - { name: shell, path: .lesskey }
        - { name: shell, path: .loadkeys }
        - { name: tmux, path: .tmux.conf }
        - { name: xresources, path: .Xresources }
        - { name: zsh, path: .zshrc }
        
    - name: set zsh as shell
      shell: |
        chsh -s /bin/zsh {{ ansible_env.USER }}
      when: ansible_facts['user_shell'] != "/bin/zsh"
