# -*- eval: (ansible +1) -*-

- hosts: all

  tasks:
    - name: get pure prompt
      git:
        repo: https://github.com/sindresorhus/pure.git
        dest: $HOME/.pure

    - name: create zfunctions directory
      file:
        state: directory
        path: $HOME/.zfunctions
        mode: 755

    - name: install pure prompt
      file:
        src: $HOME/.pure/{{ item.src }}
        dest: $HOME/.zfunctions/{{ item.dest }}
        state: link
      with_items:
        - { src: async.zsh, dest: async }
        - { src: pure.zsh, dest: prompt_pure_setup }

    - name: get dotfiles
      git:
        repo: https://github.com/bkruczyk/dotfiles.git
        dest: $HOME/.dotfiles

    - name: stow configs
      shell: |
        stow -d $HOME/.dotfiles -t $HOME bin shell tmux xresources zsh && touch $HOME/.stow
      args:
        creates: $HOME/.stow

    - name: set zsh as shell
      shell: |
        chsh -s /bin/zsh $(whoami)
      when: ansible_facts['user_shell'] != "/bin/zsh"
